---
title: Office of Performance Improvement & Innovation
timezone: UTC
collections:
  events:
    title: Events
    output: false
  initiatives:
    title: Initiatives
    output: true
    permalink: "/initiatives/:path/"
  innovation:
    title: Innovation
    output: true
    permalink: "/innovation/:path/"
  posts:
    title: Posts
    output: true
  press:
    title: Press mentions
    output: false
  projects:
    title: Projects
    output: false
  people:
    title: Staff
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: initiatives
  values:
    layout: sidebar-page
    nav_from_collection: Initiatives
- scope:
    path: ''
    type: innovation
  values:
    layout: sidebar-page
    nav_from_collection: Innovation
- scope:
    path: ''
    type: projects
  values:
    image_path: "/assets/img/projects/project-tile-placeholder.jpg"
email: ipoall@louisvilleky.government
description: 'The citizens of Louisville deserve the best city government in the country
  and Mayor Greg Fischer’s administration is committed to creating it. The Office
  of Performance Improvement & Innovation, established in January 2012, is helping
  the Mayor pursue this goal by focusing on two fundamental areas, Continuous Performance
  Improvement, and Innovation & Technology.

'
baseurl:
twitter_username: opi2lou
github_username: louisvillemetro
image: "/assets/img/home.jpg"
medium_url: https://medium.com/louisville-metro-opi2
zilker_theme: dark
theme: minima
nav_from_collection:
markdown: kramdown
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
sass:
  sass_dir: assets/stylesheets/
permalink: pretty
exclude:
- node_modules
- gulpfile.js
- Gemfile
- Gemfile.lock
- npm-debug.log
- "/screenshots"
- "/assets/stylesheets/bourbon"
- "/assets/stylesheets/bourbon-neat"
- "/assets/uswds/stylesheets"
- "/assets/uswds/js"
- ".bundle"
- "/vendor"
- _bourbon
- _bourbon-neat
- _uswds
twitter:
  username: opi2lou
logo: "/img/dti-fellows-logo.png"
