title:  "OPI2"
tagline: "a Jekyll theme for the Office of Performance Improvement & Innovation"

# Authors documented under _data

menu:
- {name: 'Innovation', folder: 'pages', file: 'facts.html'}
- {name: 'Performance Improvement', folder: 'pages', file: 'resources.html'}
- {name: 'About', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Strategic Plan', folder: 'pages', file: 'documentation.html'}
- {name: 'Mission & Core Values', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/OPI2Lou'}
- {icon: 'facebook', link: ''}
- {icon: 'instagram', link: ''}
- {icon: 'envelope', link: 'mailto:'}
- {icon: 'rss-square', link: 'feed.xml'}
